Controllers/QLChuDeController.cs
using BookShop_Online.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookShop_Online.Controllers
{
    public class QLChuDeController : Controller
    {
        // GET: QLChuDe
        private ModelBookShop _context = new ModelBookShop();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PartalChuDe()
        {
            //var lstCD = _context.ChuDes.Take(10).ToList();
            //int sluong = lstCD.Count();

            var lstCD = _context.ChuDes.Take(10).OrderBy(x => x.TenChuDe).ToList();

            //ViewBag.soluong = sluong;
            
            return PartialView(lstCD);
        }
    }
}

Controllers/QLNhaXuatBanController.cs
using BookShop_Online.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookShop_Online.Controllers
{
    public class QLNhaXuatBanController : Controller
    {
        // GET: QLNhaXuatBan
        private ModelBookShop _context = new ModelBookShop();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PartalNhaXuatBan()
        {
            var lstNXB = _context.NhaXuatBans.Take(10).ToList();
            int sluong = lstNXB.Count();
            ViewBag.soluong = sluong;
            return PartialView(lstNXB);
        }
    }
}

Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <header class="row">
            <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
                <div style="font-size: 2em;font-family:Impact; color: brown; text-shadow: 2px 2px 8px #FF0000">
                    BOOK SHOP ONLINE</div>
                <div style="color: orangered; font-style: italic; border-top: 1px dotted gray; width:60%">Express - thihoa 2024</div>
            </div>
            <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
                <img src="~/Images/logo_bookshop.png" height="100" style="float: right" />
            </div>
        </header>
        <nav class="row" style="margin-top: 20px;">
            <div class="col-12">
                <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
                    <div class="container-fluid">
                        @*<a class="navbar-brand" href="javascript:void(0)">Logo</a>*@
                        @Html.ActionLink("Trang chủ","Index","QLSach", new {@class="navbar-brand"})
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="mynavbar">
                            <ul class="navbar-nav me-auto">
                                <li class="nav-item">
                                    <a class="nav-link" href="javascript:void(0)">Link</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="javascript:void(0)">Link</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="javascript:void(0)">Link</a>
                                </li>
                            </ul>
                            <form class="d-flex">
                                <input class="form-control me-2" type="text" placeholder="Search">
                                <button class="btn btn-primary" type="button">Search</button>
                            </form>
                        </div>
                    </div>
                </nav>
            </div>
        </nav>
        <section class="row">
            <section class="col-md-9 col-lg-9 col-sm-12 col-xs-12">
                <div>
                    @RenderBody()
                </div>
            </section>
            <aside class="col-md-3 col-lg-9 col-sm-12 col-xs-12" style="float:right; width: 320px; margin-top: 20px;">
                @Html.Action("PartalChuDe", "QLChuDe")

                @*<div class="card">
                    <div class="card-header">CHỦ ĐỀ SÁCH</div>
                    <div class="card-body">Content</div>
                </div>*@

                @Html.Action("PartalNhaXuatBan","QLNhaXuatBan")

                @*<div class="card" style="margin-top: 20px;margin-bottom: 20px;">
                    <div class="card-header">NHÀ XUẤT BẢN</div>
                    <div class="card-body">Content</div>
                </div>*@
            </aside>
        </section>

        <footer class="row">
            <div class="col-12" style="background-color: burlywood; text-align:center; padding: 20px 0px; font-weight: bold">
                <div class="card-footer">Copyright &copy; thihoa 2024</div>
            </div>
        </footer>

    </div>
</body>
</html>